version: 0.2

run-as: root

phases:
  build:
    on-failure: CONTINUE
    commands:
      - ./gradlewAll publishToMavenLocal
    finally:
      - command
      - command
artifacts:
  files:
    - location
    - location
  name: kafka-build-artifact
  discard-paths: yes
  enable-symlinks: yes
  s3-prefix: prefix
